public with sharing class LeadConstants {
    public static final string DEFAULT_COMPANY_NAME = 'DON\'T KNOW';
    public static final string DEFAULT_INDUSTRY = 'Unknown';
    public static final string DEFAULT_LAST_NAME = 'Unknown';
    public static final string DEFAULT_WEBSITE = 'https://unknown.example.com';
    public static final Integer DEFAULT_NUMBER_OF_EMPLOYEES = 100;

    public static final string READY_FOR_SDR_STATUS = 'Ready for SDR';
    public static final string NEW_STATUS = 'New';
    public static final string LOST_STATUS = 'Lost';

    public static final string TRIALIST_SOURCE = 'Trialist';
    public static final string DIRECT_SOURCE = 'Direct';
    public static final string EVENT_SOURCE = 'Event';
    public static final string JOINING_TEAM_SOURCE = 'Joining team';
}
