export function fromStagePdName(name: string, pipelineId: number): number {
    const stageId = getRawStageData().find(data => data.name.trim().toLowerCase() === name.trim().toLowerCase() && data.pipeline_id === pipelineId)?.id;
    if (stageId === undefined) throw new Error(`Bad stage name: ${name} in pipeline id ${pipelineId}`);
    return stageId;
}

export function fromPdStageId(id: number): string | undefined {
    const stageName = getRawStageData().find(data => data.id === id)?.name;
    if (stageName === undefined) throw new Error(`Bad stage id: ${id}`);
    return stageName;
}

export function fromPipelinePdName(name: string): number | undefined {
    return getRawPipelineData().find(data => data.name === name)?.id;
}

export function fromPipelineId(id: number): string | undefined {
    return getRawPipelineData().find(data => data.id === id)?.name;
}

function getRawStageData() {
    return [
        {
            "id": 29,
            "order_nr": 1,
            "name": "Untriaged",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 7,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2018-01-23 11:43:47",
            "update_time": "2020-02-20 13:48:13",
            "pipeline_name": "Unqualified",
            "pipeline_deal_probability": false
        },
        {
            "id": 30,
            "order_nr": 2,
            "name": "Triaged",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 7,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2018-01-23 11:43:54",
            "update_time": "2020-02-20 13:48:13",
            "pipeline_name": "Unqualified",
            "pipeline_deal_probability": false
        },
        {
            "id": 31,
            "order_nr": 3,
            "name": "Customer replied",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 7,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2018-01-23 17:40:08",
            "update_time": "2020-02-20 13:48:13",
            "pipeline_name": "Unqualified",
            "pipeline_deal_probability": false
        },
        {
            "id": 32,
            "order_nr": 4,
            "name": "Discovery Call",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 7,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2018-03-16 17:06:19",
            "update_time": "2020-02-20 13:48:13",
            "pipeline_name": "Unqualified",
            "pipeline_deal_probability": false
        },
        {
            "id": 77,
            "order_nr": 5,
            "name": "Meeting Booked",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 7,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-04-01 18:30:28",
            "update_time": "2020-02-20 13:48:13",
            "pipeline_name": "Unqualified",
            "pipeline_deal_probability": false
        },
        {
            "id": 17,
            "order_nr": 1,
            "name": "Approaching renewal",
            "active_flag": true,
            "deal_probability": 0,
            "pipeline_id": 4,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2017-07-11 10:04:56",
            "update_time": "2017-07-11 10:05:26",
            "pipeline_name": "Renewals",
            "pipeline_deal_probability": false
        },
        {
            "id": 18,
            "order_nr": 2,
            "name": "Contacted for renewal opportunity",
            "active_flag": true,
            "deal_probability": 0,
            "pipeline_id": 4,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2017-07-11 10:05:10",
            "update_time": "2017-07-11 10:05:26",
            "pipeline_name": "Renewals",
            "pipeline_deal_probability": false
        },
        {
            "id": 19,
            "order_nr": 3,
            "name": "Licensing negotiation",
            "active_flag": true,
            "deal_probability": 0,
            "pipeline_id": 4,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2017-07-11 10:05:20",
            "update_time": "2017-07-11 10:05:26",
            "pipeline_name": "Renewals",
            "pipeline_deal_probability": false
        },
        {
            "id": 20,
            "order_nr": 4,
            "name": "Invoice issued",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 4,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2017-07-11 10:05:26",
            "update_time": "2018-02-22 11:50:35",
            "pipeline_name": "Renewals",
            "pipeline_deal_probability": false
        },
        {
            "id": 41,
            "order_nr": 1,
            "name": "Opportunity Identified",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 9,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2018-06-07 15:01:27",
            "update_time": "2018-06-07 15:02:59",
            "pipeline_name": "Expansions",
            "pipeline_deal_probability": false
        },
        {
            "id": 42,
            "order_nr": 2,
            "name": "Champion Contacted",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 9,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2018-06-07 15:01:46",
            "update_time": "2018-06-07 15:02:59",
            "pipeline_name": "Expansions",
            "pipeline_deal_probability": false
        },
        {
            "id": 43,
            "order_nr": 3,
            "name": "Opportunity Confirmed",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 9,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2018-06-07 15:02:08",
            "update_time": "2018-06-07 15:02:59",
            "pipeline_name": "Expansions",
            "pipeline_deal_probability": false
        },
        {
            "id": 44,
            "order_nr": 4,
            "name": "Licensing Negotiation",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 9,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2018-06-07 15:02:36",
            "update_time": "2018-06-07 15:07:17",
            "pipeline_name": "Expansions",
            "pipeline_deal_probability": false
        },
        {
            "id": 45,
            "order_nr": 5,
            "name": "Quote Sent",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 9,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2018-06-07 15:02:46",
            "update_time": "2018-06-07 15:03:05",
            "pipeline_name": "Expansions",
            "pipeline_deal_probability": false
        },
        {
            "id": 46,
            "order_nr": 6,
            "name": "Invoice Out",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 9,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2018-06-07 15:02:59",
            "update_time": "2018-06-07 15:02:59",
            "pipeline_name": "Expansions",
            "pipeline_deal_probability": false
        },
        {
            "id": 58,
            "order_nr": 2,
            "name": "Discovery",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 11,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2018-10-24 09:19:06",
            "update_time": "2019-04-01 18:35:24",
            "pipeline_name": "Qualified Pipeline",
            "pipeline_deal_probability": false
        },
        {
            "id": 59,
            "order_nr": 3,
            "name": "Solution Validating",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 11,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2018-10-24 09:19:37",
            "update_time": "2019-04-01 18:35:24",
            "pipeline_name": "Qualified Pipeline",
            "pipeline_deal_probability": false
        },
        {
            "id": 60,
            "order_nr": 4,
            "name": "Negotiations and Approvals",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 11,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2018-10-24 09:19:54",
            "update_time": "2019-04-01 18:35:24",
            "pipeline_name": "Qualified Pipeline",
            "pipeline_deal_probability": false
        },
        {
            "id": 61,
            "order_nr": 5,
            "name": "Procurement",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 11,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2018-10-24 09:20:06",
            "update_time": "2019-04-01 18:35:24",
            "pipeline_name": "Qualified Pipeline",
            "pipeline_deal_probability": false
        },
        {
            "id": 62,
            "order_nr": 6,
            "name": "Invoice Issued",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 11,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2018-10-29 11:49:54",
            "update_time": "2019-04-01 18:35:24",
            "pipeline_name": "Qualified Pipeline",
            "pipeline_deal_probability": false
        },
        {
            "id": 78,
            "order_nr": 1,
            "name": "Untriaged",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 15,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-05-23 10:42:16",
            "update_time": "2019-06-14 09:52:31",
            "pipeline_name": "Outbound",
            "pipeline_deal_probability": false
        },
        {
            "id": 79,
            "order_nr": 2,
            "name": "Triaged",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 15,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-05-23 10:42:27",
            "update_time": "2019-06-14 09:52:31",
            "pipeline_name": "Outbound",
            "pipeline_deal_probability": false
        },
        {
            "id": 94,
            "order_nr": 3,
            "name": "Connect Accepted",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 15,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-06-14 09:52:27",
            "update_time": "2019-06-14 09:52:31",
            "pipeline_name": "Outbound",
            "pipeline_deal_probability": false
        },
        {
            "id": 91,
            "order_nr": 4,
            "name": "Customer Replied",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 15,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-05-29 12:45:24",
            "update_time": "2019-06-14 09:52:31",
            "pipeline_name": "Outbound",
            "pipeline_deal_probability": false
        },
        {
            "id": 92,
            "order_nr": 5,
            "name": "Discovery Call",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 15,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-05-29 12:45:36",
            "update_time": "2019-06-14 09:52:31",
            "pipeline_name": "Outbound",
            "pipeline_deal_probability": false
        },
        {
            "id": 93,
            "order_nr": 6,
            "name": "Meeting Booked",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 15,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-05-29 12:45:43",
            "update_time": "2019-06-14 09:52:31",
            "pipeline_name": "Outbound",
            "pipeline_deal_probability": false
        },
        {
            "id": 95,
            "order_nr": 1,
            "name": "Prospecting ",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 17,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-08-13 15:09:40",
            "update_time": "2019-08-15 10:15:47",
            "pipeline_name": "Account Management",
            "pipeline_deal_probability": true
        },
        {
            "id": 96,
            "order_nr": 2,
            "name": "Discovery",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 17,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-08-15 10:15:47",
            "update_time": "2019-08-15 10:15:47",
            "pipeline_name": "Account Management",
            "pipeline_deal_probability": true
        },
        {
            "id": 97,
            "order_nr": 3,
            "name": "Solution Validating ",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 17,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-08-15 10:15:47",
            "update_time": "2019-08-15 10:15:47",
            "pipeline_name": "Account Management",
            "pipeline_deal_probability": true
        },
        {
            "id": 98,
            "order_nr": 4,
            "name": "Negotiations and Approvals ",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 17,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-08-15 10:15:47",
            "update_time": "2019-08-15 10:15:47",
            "pipeline_name": "Account Management",
            "pipeline_deal_probability": true
        },
        {
            "id": 99,
            "order_nr": 5,
            "name": "Procurement ",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 17,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-08-15 10:15:47",
            "update_time": "2019-08-15 10:15:47",
            "pipeline_name": "Account Management",
            "pipeline_deal_probability": true
        },
        {
            "id": 100,
            "order_nr": 6,
            "name": "Invoice Issued",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 17,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-08-15 10:15:47",
            "update_time": "2019-08-15 10:15:47",
            "pipeline_name": "Account Management",
            "pipeline_deal_probability": true
        },
        {
            "id": 101,
            "order_nr": 1,
            "name": "Lead In",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 18,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-09-04 08:29:38",
            "update_time": "2019-09-04 08:29:38",
            "pipeline_name": "Backup",
            "pipeline_deal_probability": true
        },
        {
            "id": 125,
            "order_nr": 1,
            "name": "Onboarding",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 25,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2020-03-11 13:34:56",
            "update_time": "2020-03-24 08:55:06",
            "pipeline_name": "Customer Success",
            "pipeline_deal_probability": false
        },
        {
            "id": 102,
            "order_nr": 2,
            "name": "Discover call arranged",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 18,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-09-04 08:29:38",
            "update_time": "2019-09-04 08:29:38",
            "pipeline_name": "Backup",
            "pipeline_deal_probability": true
        },
        {
            "id": 126,
            "order_nr": 2,
            "name": "Ramped",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 25,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2020-03-11 13:34:56",
            "update_time": "2020-03-24 08:55:06",
            "pipeline_name": "Customer Success",
            "pipeline_deal_probability": false
        },
        {
            "id": 103,
            "order_nr": 3,
            "name": "Discovery call completed",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 18,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-09-04 08:29:38",
            "update_time": "2019-09-04 08:29:38",
            "pipeline_name": "Backup",
            "pipeline_deal_probability": true
        },
        {
            "id": 127,
            "order_nr": 3,
            "name": "Churn Risk - Attempting Contact",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 25,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2020-03-11 13:34:56",
            "update_time": "2020-03-24 08:55:06",
            "pipeline_name": "Customer Success",
            "pipeline_deal_probability": false
        },
        {
            "id": 104,
            "order_nr": 4,
            "name": "Solution validating",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 18,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-09-04 08:29:38",
            "update_time": "2019-09-04 08:29:38",
            "pipeline_name": "Backup",
            "pipeline_deal_probability": true
        },
        {
            "id": 128,
            "order_nr": 4,
            "name": "Churn Risk - In Discussion",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 25,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2020-03-11 13:34:56",
            "update_time": "2020-03-24 08:55:06",
            "pipeline_name": "Customer Success",
            "pipeline_deal_probability": false
        },
        {
            "id": 105,
            "order_nr": 5,
            "name": "Negotiations Started",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 18,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2019-09-04 08:29:38",
            "update_time": "2019-09-04 08:29:38",
            "pipeline_name": "Backup",
            "pipeline_deal_probability": true
        },
        {
            "id": 129,
            "order_nr": 5,
            "name": "Churned",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 25,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2020-03-11 13:34:56",
            "update_time": "2020-03-24 08:55:06",
            "pipeline_name": "Customer Success",
            "pipeline_deal_probability": false
        },
        {
            "id": 130,
            "order_nr": 1,
            "name": "Scanned",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 26,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2020-03-11 19:08:09",
            "update_time": "2020-03-11 19:08:09",
            "pipeline_name": "Events",
            "pipeline_deal_probability": false
        },
        {
            "id": 131,
            "order_nr": 2,
            "name": "Triaged",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 26,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2020-03-11 19:08:09",
            "update_time": "2020-03-11 19:08:09",
            "pipeline_name": "Events",
            "pipeline_deal_probability": false
        },
        {
            "id": 132,
            "order_nr": 3,
            "name": "Contact1",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 26,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2020-03-11 19:08:09",
            "update_time": "2020-03-11 19:08:09",
            "pipeline_name": "Events",
            "pipeline_deal_probability": false
        },
        {
            "id": 133,
            "order_nr": 4,
            "name": "Contact2",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 26,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2020-03-11 19:08:09",
            "update_time": "2020-03-11 19:08:09",
            "pipeline_name": "Events",
            "pipeline_deal_probability": false
        },
        {
            "id": 134,
            "order_nr": 5,
            "name": "Contact3",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 26,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2020-03-11 19:08:09",
            "update_time": "2020-03-11 19:08:09",
            "pipeline_name": "Events",
            "pipeline_deal_probability": false
        },
        {
            "id": 135,
            "order_nr": 6,
            "name": "Contact4",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 26,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2020-03-11 19:08:09",
            "update_time": "2020-03-11 19:08:09",
            "pipeline_name": "Events",
            "pipeline_deal_probability": false
        },
        {
            "id": 136,
            "order_nr": 7,
            "name": "Contact5",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 26,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2020-03-11 19:08:09",
            "update_time": "2020-03-11 19:08:09",
            "pipeline_name": "Events",
            "pipeline_deal_probability": false
        },
        {
            "id": 137,
            "order_nr": 8,
            "name": "Replied",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 26,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2020-03-11 19:08:09",
            "update_time": "2020-03-11 19:08:09",
            "pipeline_name": "Events",
            "pipeline_deal_probability": false
        },
        {
            "id": 138,
            "order_nr": 9,
            "name": "Interested",
            "active_flag": true,
            "deal_probability": 100,
            "pipeline_id": 26,
            "rotten_flag": false,
            "rotten_days": null,
            "add_time": "2020-03-11 19:08:09",
            "update_time": "2020-03-11 19:08:09",
            "pipeline_name": "Events",
            "pipeline_deal_probability": false
        }
    ];
}

function getRawPipelineData() {
    return [
        {
            "id": 7,
            "name": "Unqualified",
            "url_title": "Unqualified",
            "order_nr": 1,
            "active": true,
            "deal_probability": false,
            "add_time": "2018-01-23 11:43:08",
            "update_time": "2019-05-17 11:47:29",
            "selected": true
        },
        {
            "id": 4,
            "name": "Renewals",
            "url_title": "Renewals",
            "order_nr": 2,
            "active": true,
            "deal_probability": false,
            "add_time": "2017-07-11 10:04:42",
            "update_time": "2018-06-07 15:03:38",
            "selected": false
        },
        {
            "id": 9,
            "name": "Expansions",
            "url_title": "Expansions",
            "order_nr": 3,
            "active": true,
            "deal_probability": false,
            "add_time": "2018-06-07 15:01:02",
            "update_time": "2018-06-07 15:03:38",
            "selected": false
        },
        {
            "id": 11,
            "name": "Qualified Pipeline",
            "url_title": "Qualified-Pipeline",
            "order_nr": 8,
            "active": true,
            "deal_probability": false,
            "add_time": "2018-10-24 09:17:44",
            "update_time": "2018-10-24 09:17:56",
            "selected": false
        },
        {
            "id": 15,
            "name": "Outbound",
            "url_title": "Outbound",
            "order_nr": 9,
            "active": true,
            "deal_probability": false,
            "add_time": "2019-05-23 10:41:58",
            "update_time": "2019-05-23 10:41:58",
            "selected": false
        },
        {
            "id": 17,
            "name": "Account Management",
            "url_title": "Account-Management",
            "order_nr": 11,
            "active": true,
            "deal_probability": true,
            "add_time": "2019-08-13 15:09:40",
            "update_time": "2019-08-13 15:09:40",
            "selected": false
        },
        {
            "id": 18,
            "name": "Backup",
            "url_title": "Backup",
            "order_nr": 12,
            "active": true,
            "deal_probability": true,
            "add_time": "2019-09-04 08:29:38",
            "update_time": "2019-09-04 08:29:38",
            "selected": false
        },
        {
            "id": 25,
            "name": "Customer Success",
            "url_title": "Customer Success1",
            "order_nr": 12,
            "active": true,
            "deal_probability": false,
            "add_time": "2020-03-11 13:34:56",
            "update_time": "2020-03-20 13:09:03",
            "selected": false
        },
        {
            "id": 26,
            "name": "Events",
            "url_title": "Events",
            "order_nr": 13,
            "active": true,
            "deal_probability": false,
            "add_time": "2020-03-11 19:08:09",
            "update_time": "2020-03-11 19:08:09",
            "selected": false
        }
    ];
}